import '../globals.css'
import { Header, Footer } from '@/components/Layout'

export const metadata = {
  description: 'Generated by Spaceverse',
  title: 'Spaceverse',
}

export default function ContentRootLayout({ children }) {
  return (
    <div className="bg-black min-h-screen flex flex-col justify-between">
      <Header />
      {children}
      <Footer />
    </div>
  )
}
